# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  name: linux-vm  # your self-hosted agent pool

variables:
  ACR_LOGIN_SERVER: $(ACR_LOGIN_SERVER)
  IMAGE_NAME: trackpulse
  WEBAPP_NAME: $(AZURE_CONTAINER_WEBAPP_NAME)

steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: acr-service-connection  # set this up in Project Settings

  - task: Docker@2
    displayName: Build and push image
    inputs:
      command: buildAndPush
      repository: $(IMAGE_NAME)
      dockerfile: Dockerfile
      containerRegistry: acr-service-connection
      tags: latest
      arguments: --build-arg NEXT_PUBLIC_APP_URL=$(NEXT_PUBLIC_APP_URL)

  - task: AzureWebAppContainer@1
    displayName: Deploy to Azure App Service
    inputs:
      azureSubscription: azure-service-connection  # set this up in Project Settings
      appName: $(WEBAPP_NAME)
      containers: $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):latest
