apiVersion: v1
kind: Service
metadata:
  name: trackpulse-service
  namespace: trackpulse
spec:
  selector:
    app: trackpulse
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
