apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: trackpulse
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: trackpulseregistry.azurecr.io/trackpulse:latest
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - npx --yes prisma@5.14.0 db push
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: trackpulse-secrets
                  key: DATABASE_URL
      imagePullSecrets:
        - name: acr-pull-secret
